---
- name: Reload systemd
  sudo: yes
  command: systemctl --system daemon-reload

- name: Reload systemd-timesyncd
  sudo: yes
  command: systemctl restart systemd-timesyncd

- name: Enable ntp
  sudo: yes
  command: timedatectl set-ntp true
  notify: Reload systemd-timesyncd

- name: Run logrotate
  become: yes
  command: /usr/sbin/logrotate -fv /etc/logrotate.d/docker-container-logrotate
